### ISSUE TITLE
non-zero diffuse electricity absoprtance in BSDF systems with no PV data

### ISSUE THREAD

**Issue by StephenCzarnecki** [LBNL-ETA/Windows-CalcEngine#110]
BSDF systems with no PV data are returning non-zero diffuse electricity absoprtance values.  I think this is because in CMultiPaneBSDF::getAbsorptanceLayersElectricity the diffuse case calls AbsDiffuse.  Compare to CMultiPaneSpecular which calls CMultiPaneSpecular::getAbsorptanceLayerElectricity instead.  The same is true for heat.

Made a change to unit tests to create a failing test to show the issue.  See change made in https://github.com/LBNL-ETA/Windows-CalcEngine/commit/7dabbe8b19ac70d0fbfc066d5cb21531d69f7707

**Comment by vidanovic** [comment]
Fixed in Version_1.0.27
