### ISSUE TITLE
BSDF system results disagrees with WINDOW 7.8.43

### ISSUE THREAD

**Issue by StephenCzarnecki** [LBNL-ETA/Windows-CalcEngine#111]
A user was asking about a difference in results between WINDOW and pywincalc.  They had other issues as well but in the course of investigating I noticed a system that had results that seemed quite different from what WINDOW was giving.

The system is a double layer with NFRC 102 and 2011-SA1.XML

WINDOW optical calc preferences:

![image](https://user-images.githubusercontent.com/7605407/167487862-14ea395d-208a-452d-a6f9-004af1acd9fb.png)

WINDOW 7.8.43 system and results:

![image](https://user-images.githubusercontent.com/7605407/167488025-19e22f0c-a202-45cb-8b05-c02c393ed2a3.png)

I made a unit test with the BSDF matrices from the system and put in the results from WINDOW here: https://github.com/LBNL-ETA/Windows-CalcEngine/blob/PVRefactoring/src/MultiLayerOptics/tst/units/MultiPaneBSDF_102_BSDFMaterial_2011-SA1.unit.cpp

**Comment by vidanovic** [comment]
One fix was #112 while other problem is in WINDOW. WINDOW is not scaling solar and visible matrices appropriately when doing XML layer type.
