### ISSUE TITLE
New NIR scaling for materials that have only solar and visible data

### ISSUE THREAD

**Issue by vidanovic** [LBNL-ETA/Windows-CalcEngine#129]
There are materials defined only with already integrated numbers in solar and visible spectrum. In order to do more accurate calculations implement algorithm that is proposed for WINDOW as well. Some scaling is already done, however, @jcjonsson have write up about some changes to it (non zero values between 0.3 and 0.32 and scale factor is 0.499)

**Comment by jcjonsson** [comment]
G:\Shared drives\Window\WindowDoc\Window Calculation Procedures\Dual band multilayer calculation implementation_new.doc
Its not a great file name as it is not really about multilayer calcs. Just the Dual band part.
