### ISSUE TITLE
Absorptance heat is incorrectly calculated in CMultiPaneBSDF

### ISSUE THREAD

**Issue by vidanovic** [LBNL-ETA/Windows-CalcEngine#152]
Aborptance heat calculation in CMultiPaneBSDF is using incorrect size for the loop.

**Comment by RDmitchell** [comment]
@vidanovic -- is this true in the WINDOW 7 code also? Or just in the WinCalc Engine?

**Comment by vidanovic** [comment]
# Fixed in Version_1.0.39

**Comment by vidanovic** [comment]
@RDmitchell This is WinCalc-Engine. Fixed since @StephenCzarnecki is going to use it now.
