### ISSUE TITLE
Ventilated gap calculations for layer that is not shade

### ISSUE THREAD

**Issue by vidanovic** [LBNL-ETA/Windows-CalcEngine#155]
Currently, the ventilated gap calculations are called only in the case when shading layer has been created. Make changes so that ventilation calculations are called in any case, even with glass layer.

**Comment by RDmitchell** [comment]
This is something that Fraunhoffer is testing. When @vidanovic merges their code, then we can test this.

**Comment by vidanovic** [comment]
# Fixed in 1.0.40
