### ISSUE TITLE
Gap gets connected to the interior environment even if layer is not porous

### ISSUE THREAD

**Issue by vidanovic** [LBNL-ETA/Windows-CalcEngine#97]
If we have for example double layer that have exterior shade, airflow of gap should not be accounted for U-value. This is however not true and interior layer must be marked as porous in order to fix this.

**Comment by vidanovic** [comment]
Fixed

**Comment by RDmitchell** [comment]
@vidanovic -- what shading systems does this affect? Does it affect venetian blinds? 

I'm trying to figure out if this fix should be included in the NFRC 7.8 version.

Also, I assume this is WINDOW??

**Comment by vidanovic** [comment]
No. This is WCE. No affects to the WINDOW.

**Comment by RDmitchell** [comment]
Ah yes, I didn't even look at which repo it was for. duh ...

**Comment by vidanovic** [comment]
No problem
